FROM node:18.16.0-alpine

# Declaring env
#ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Copy package.json & package-lock.json to work directory
COPY package*.json ./

# Installing dependencies
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm run dev

# Exposing server port
EXPOSE 3000